a1 = input("Enter the first number:")
a2 = input("Enter the second number:")
a3 = int(a1) / int(a2)
print(a3)
b1 = input("Enter the first number:")
b2 = input("Enter the second number:")
b3 = int(b1) % int(b2)
print(b3)
c1 = input("Enter the first number:")
c2 = input("Enter the second number:")
c3 = int(c1) ** int(c2)
print(c3)
